fs/crypto: fix compilation error error: use of undeclared label 'fail_free_info'
* Actually no idea why this error gets triggered since CONFIG_FSCRYPT_SDP is enabled in defconfig. well...